services:
  pulse-ingestor:
    container_name: pulse-ingestor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${INGESTOR_PORT}:${INGESTOR_PORT}'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - pulse-ingestor-network

  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port ${REDIS_PORT} --appendonly yes --save ""
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - pulse-ingestor-network

volumes:
  redis:
    driver: local

networks:
  pulse-ingestor-network:
    name: pulse-ingestor-network
    driver: bridge
