services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --maxclients 10000 --tcp-backlog 511 --timeout 0 --save "" --appendonly no
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    networks:
      - pulse-ingestor-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pulse-ingestor-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - pulse-ingestor-network

volumes:
  grafana-storage:
    driver: local
  redis:
    driver: local

networks:
  pulse-ingestor-network:
    name: pulse-ingestor-network
    driver: bridge
