services:
  pulse-ingestor:
    container_name: pulse-ingestor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${INGESTOR_PORT}:${INGESTOR_PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - pulse-ingestor-network

  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port ${REDIS_PORT} --appendonly yes --save ""
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - pulse-ingestor-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - pulse-ingestor
    networks:
      - pulse-ingestor-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - pulse-ingestor-network

volumes:
  grafana-storage:
    driver: local
  redis:
    driver: local

networks:
  pulse-ingestor-network:
    name: pulse-ingestor-network
    driver: bridge
